### ISSUE TITLE
Tomcat: exception when deploying syncope.war with a DB with existing user and memberships

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/syncope#37]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on August 03, 2010 17:18:19_

With Tomcat 6, when deploying syncope.war with a DB instance containing at least one user with memberships, the following stacktrace is thrown:

GRAVE: Exception sending context initialized event to listener instance of class org.syncope.core.persistence.ConnectorInstanceBeansLoader
javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not initialize a collection: [org.syncope.core.persistence.beans.role.SyncopeRole.memberships#10]
        at org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:614)
        at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:76)
        at org.syncope.core.persistence.dao.impl.ConnectorInstanceDAOImpl.findAll(ConnectorInstanceDAOImpl.java:36)
        at org.syncope.core.persistence.ConnectorInstanceBeansLoader.contextInitialized(ConnectorInstanceBeansLoader.java:66)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3972)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4467)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:905)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:740)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:500)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1345)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:303)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1337)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1601)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1610)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1590)
        at java.lang.Thread.run(Thread.java:637)
Caused by: org.hibernate.exception.GenericJDBCException: could not initialize a collection: [org.syncope.core.persistence.beans.role.SyncopeRole.memberships#10]
        at org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:126)
        at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:114)
        at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
        at org.hibernate.loader.Loader.loadCollection(Loader.java:2022)
        at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:59)
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:587)
        at org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:83)
        at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1743)
        at org.hibernate.collection.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:476)
        at org.hibernate.engine.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:867)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:264)
        at org.hibernate.loader.Loader.doList(Loader.java:2228)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2125)
        at org.hibernate.loader.Loader.list(Loader.java:2120)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:401)
        at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:361)
        at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)
        at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1148)
        at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)
        at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:67)
        ... 18 more
Caused by: org.postgresql.util.PSQLException: Non è possibile impostare i «Large Object» in modalità «auto-commit».
        at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:200)
        at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:172)
        at org.postgresql.jdbc2.AbstractJdbc2BlobClob.<init>(AbstractJdbc2BlobClob.java:47)
        at org.postgresql.jdbc2.AbstractJdbc2Blob.<init>(AbstractJdbc2Blob.java:21)
        at org.postgresql.jdbc3.AbstractJdbc3Blob.<init>(AbstractJdbc3Blob.java:19)
        at org.postgresql.jdbc4.AbstractJdbc4Blob.<init>(AbstractJdbc4Blob.java:20)
        at org.postgresql.jdbc4.Jdbc4Blob.<init>(Jdbc4Blob.java:20)
        at org.postgresql.jdbc4.Jdbc4ResultSet.getBlob(Jdbc4ResultSet.java:52)
        at org.postgresql.jdbc2.AbstractJdbc2ResultSet.getBlob(AbstractJdbc2ResultSet.java:335)
        at org.hibernate.type.ByteArrayBlobType.get(ByteArrayBlobType.java:87)
        at org.hibernate.type.AbstractLobType.nullSafeGet(AbstractLobType.java:46)
        at org.hibernate.type.AbstractType.hydrate(AbstractType.java:105)
        at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2124)
        at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1404)
        at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1332)
        at org.hibernate.loader.Loader.getRow(Loader.java:1230)
        at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:603)
        at org.hibernate.loader.Loader.doQuery(Loader.java:724)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)
        at org.hibernate.loader.Loader.loadCollection(Loader.java:2015)
        ... 34 more

_Original issue: http://code.google.com/p/syncope/issues/detail?id=29_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 16, 2010 08:30:18_

**Status:** Invalid
