### ISSUE TITLE
ORA-00060 (deadlock) with Oracle DB and parallel user creation requests

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/syncope#77]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on November 23, 2010 14:54:36_

When requesting at least 5 concurrent user creations - while using Oracle DB as storage - some of those requests (one, usually) gets an Exception

12:09:50.498 ERROR org.hibernate.event.def.AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.LockAcquisitionException: Could not execute JDBC batch update
[...]
at org.syncope.core.persistence.dao.impl.AbstractDAOImpl.flush(AbstractDAOImpl.java:46)
[...]
at it.everett.prcsiam.syncope.core.workflow.EmptyUser.execute(EmptyUser.java:66)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=69_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on November 23, 2010 09:04:46_

This issue was closed by revision r697 .

**Status:** Fixed
